### ISSUE TITLE
Action ordering lost

### ISSUE THREAD

**Issue by Pastim** [puddletag/puddletag#586]
On ubuntu 20.10, puddletag 2.0.1, PyQt 5.15.0, Mutagen 1.45.0, Pyparsing 2.4.7.

I have some complex multi-step actions that must be run in the order specified.  This always used to work.  I haven't done any tagging for quite a while now (several months), but now when I tried the action steps are muddled up.  So I looked at the .local/share/puddletag/actions file, and it all looks to be correct.  But the display in puddletag is wrong.  I tried moving items around to correct the problem, but the order is quickly lost and the items muddled up again in puddletag, but not in the action file.

**Comment by Pastim** [comment]
I thought I'd try using the current Master version.  All is OK!  I have no idea which change from the ubuntu standard repo 2.0.1 fixed the issue, but it is fixed.

May be getting to the time for a 2.0.2 release ?

**Comment by Pastim** [comment]
Only an issue in the standard 2.0.1 release now.

**Comment by sandrotosi** [comment]
> May be getting to the time for a 2.0.2 release ?

yes it is, but i still have a few more items i want to tackle before releasing a new version
